CREATE TABLE account(
  id CHAR(26) PRIMARY KEY NONCLUSTERED,
  balance INT CHECK (balance >= 0),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);